### ISSUE TITLE
Pasting an En dash (–) crashes

### ISSUE THREAD

**Issue by FluXy** [cegui/ceed-cpp#112]
Pasting only tested with Label and StaticText.

---

For loading:
- When loading a layout file where it's (–) already in the "Text" property an exception happens:
> CEGUI::UnicodeStringException in function 'void __cdecl CEGUI::String::checkUtf8CodePointSizeForValidity(const unsigned int,const unsigned int)' (C:\Personal\Repos\cegui\cegui\src\String.cpp:298) : Invalid initial byte detected for a code point in the string

Which seems correct but it would be nice if it only ignores that character and not the whole .layout file

- When loading a layout file where it's as XML (`&#x2013;`) already in the "Text" property it works.

---

CEED-v1.1.1-Win-x86

The en dash is like a hyphen (-) but slightly longer (–).
https://en.wikipedia.org/wiki/Dash#En_dash

**Comment by niello** [comment]
@FluXy can you build CEED with this fix? I wouldn't prepare a separate release for it unless absolutely inevitable.

**Comment by niello** [comment]
[ceed.exe.txt](https://github.com/cegui/ceed-cpp/files/8309464/ceed.exe.txt)

Here is an alternative. Simply remove ".txt"

**Comment by FluXy** [comment]
Thanks for the quick fix! Works fine now

**Comment by niello** [comment]
I had overcome my laziness and released 1.1.2 with this fix and a couple of additional improvements. Enjoy and feel free to report problems)
