### ISSUE TITLE
Update checks and distribution

### ISSUE THREAD

**Issue by vorlov-playrix** [cegui/ceed-cpp#40]
When a new release is created on GitHub, CEED must be able to detect and download it

- [x] Command to check for updates
- [x] Automatic check for updates at each launch
- [x] Update info dialog
- [x] Get the latest release version and determine if we should update to it (no draft, no pre-release)
- [x] Remember if update exists? Or re-check every time?
- [x] Find and download an asset
- [x] Unzip asset and save SHA/Version somewhere to verify that it is already downloaded
- [x] Save to settings the version we going to update to, to detect failure on restart
- [x] Generate and run batch and close an application
- [x] Batch must wait for the process exit
- [x] Copy files with tmp buffering to avoid corruption of an old installation
- [x] If copy failed restore old installation and delete trash
- [x] If copy OK delete old tmp and new tmp and run an application
- [x] Show dialog with successful or failed update info
- [x] Cleanup tmp files after update
- [x] Remember failed update to skip it until the newer version is available?
- [x] Uncomment version check!
- [x] Uncomment application exit!
- [x] Uncomment checking asset size!
- [x] Change "Editor.exe" to "ceed.exe" in a script!

Get the latest release info: https://api.github.com/repos/cegui/ceed-cpp/releases/latest

Wait for the process to finish (can exit loop after some retrials):
```
:loop
tasklist | find " MY_PID_OR_EXE_NAME " >nul
if not errorlevel 1 (
    timeout /t 10 >nul
    goto :loop
)
```

also can check by the full path:
`
wmic process where "ExecutablePath like '%\\ceed%.exe'" get ExecutablePath | findstr "ceed*.exe"
`

**Comment by niello** [comment]
Done
