### ISSUE TITLE
Children of a FrameWindow are misplaced on load

### ISSUE THREAD

**Issue by vorlov-playrix** [cegui/ceed-cpp#44]
Repro:

1. Create a new layout
2. Add a FrameWindow
3. Add a child button
4. Either switch to Code and back to Visual, close and reload a layout file or close and reload an application

Button is rendered several pixels above its manipulator and expected position. Dragging a manipulator immediately fixes this for this particular button, not fixing other child elements.

**Comment by vorlov-playrix** [comment]
Reason: in onParentSized we don't consider a child moved in a case where it is possible due to parent inner rect shift, e.g. when FrameWindow recalculates its size and updates a titlebar height.

**Comment by niello** [comment]
Fixed after 1 month of rewriting CEGUI core xD
