### ISSUE TITLE
Crash on multuple widget deletion

### ISSUE THREAD

**Issue by vorlov-playrix** [cegui/ceed-cpp#46]
Repro:

1. Load [1.layout.txt](https://github.com/cegui/ceed-cpp/files/6730903/1.layout.txt)
2. Ctrl+A to select all widgets
3. Ctrl+Click on root in a window hierarchy to deselect root
4. Del

Crash happens in QtnMultiProperty.

**Comment by niello** [comment]
Also deleting left, then center, then Ctrl+A except root, then restoring them with Ctrl+Z also crashes in Qtn
