### ISSUE TITLE
TabControl support

### ISSUE THREAD

**Issue by vorlov-playrix** [cegui/ceed-cpp#47]
- [x] Support custom right click menu
- [x] Add new tab
- [x] Rename tab (reset selection to the tab only and focus on Text property or in-scene QGraphicsTextItem?)
- [x] Remove tab
- [x] Set tab current
- [x] Disable moving and sizing of tab windows (immediate children of pane)
- [x] On add tab ensure some default text is assigned at least for DefaultWindow / context menu adding
- [x] Fix manipulator offset (drop button on the tab and you will see)

**Comment by niello** [comment]
Done
