### ISSUE TITLE
Crash on creating layout without a project loaded

### ISSUE THREAD

**Issue by niello** [cegui/ceed-cpp#91]
1. Download fresh CEED 1.1.0 to a new folder
2. Run an application
3. Menu - Create - Layout
4. Application crashes

Tested on Win 11 but probably is OS-independent

**Comment by vorlov-playrix** [comment]
Not reproducing on Win 10

**Comment by utopic-releases** [comment]
Reproduced in Windows 7 Ultimate x86....

**Comment by niello** [comment]
@utopic-releases are repro steps the same? Can you provide a callstack if you are able to build CEED locally?
